datasets:
  train:
    n_iter: 120000
    batch_size: 4
    use_shuffle: True
    n_workers: 4
    img_shape: [3, 256, 256]  # [channel, height, width]
    img_height: 256
    img_width: 256
    image_list: 'datasets/celeba-hq/celeba_hq_train.txt'
    mask_list: ''
    mask_type: 'regular' # regular vs center
    mask_pos: 'random' # random vs center
    mask_height: 128
    mask_width: 128
    vertical_margin: 0
    horizontal_margin: 0
    max_delta_height: 0
    max_delta_width: 0
  val:
    name: 'celeba_val'
    batch_size: 4
    use_shuffle: True
    n_workers: 4
    img_shape: [3, 256, 256]  # [channel, height, width]
    img_height: 256
    img_width: 256
    image_list: 'datasets/celeba-hq/celeba_hq_val.txt'
    mask_list: ''
    mask_type: 'regular'
    mask_pos: 'random'
    mask_height: 128
    mask_width: 128
    vertical_margin: 0
    horizontal_margin: 0
    max_delta_height: 0
    max_delta_width: 0
  test:
    name: 'celeba_test'
    batch_size: 1
    use_shuffle: False
    n_workers: 1
    img_shape: [3, 256, 256]
    img_height: 256
    img_width: 256
    image_list: 'datasets/celeba-hq/celeba_val.txt'
    mask_list: 'datasets/celeba-hq/celeba_mask.txt'
    mask_type: 'irregular'
    mask_pos: 'random'
    mask_height: 128
    mask_width: 128
    vertical_margin: 0
    horizontal_margin: 0
    max_delta_height: 0
    max_delta_width: 0


img_shape: [3, 256, 256]  # [channel, height, width]
img_height: 256
img_width: 256

is_train: True
gpu_ids: []
# pretrained_model_G: 'outputs/celeba-hq/checkpoints/58000_G.pth'
pretrained_model_G: ''
pretrained_model_D: ''
val_iter: 250
log_iter: 250
save_image_iter: 1000
save_model_iter: 10000
display_num: 8

network_G:
  # which_model_G: 'inpainting_resnet'
  which_model_G: 'DMFN'
  in_nc: 4
  out_nc: 3
  nf: 64
  n_res: 8

network_D:
  which_model_D: 'discriminator'
  in_nc: 3
  nf: 64


# train options
train:
  pixel_weight: 1
  pixel_criterion: 'l1'  # [l1 | ml1]
  feature_weight: 25
  feature_criterion: 'l1'
  center_weight: 1
  dis_feature_weight: 5
  dis_feature_criterion: 'l1'
  gan_weight: 0.003
  gan_type: 'vanilla'  # vanilla | lsgan
  lr_G: 0.0002
  lr_D: 0.0002
  lr_policy: 'MultiStepLR'
  lr_steps: [100000]
  lr_gamma: 0.5
